spring:
  application:
    name: Config-Default
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-wicyh-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
